name: flutter_supabase_notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  supabase_flutter: ^2.5.2
  get_storage: ^2.1.1
  path_provider: ^2.1.3
  image_picker: ^1.0.7
  file_picker: ^10.2.0

  dotted_border: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/IKON.jpg" # Sesuaikan path ke file ikon Anda
  min_sdk_android: 21 # optional
  
flutter:
  uses-material-design: true